Translate radio/checkbox values when using bp_get_member_profile_data()
OnTheGoSystems/buddypress-multilingual pull request #27
Opened 2021-11-17 17:56 UTC by dgwatkins

Took the chance to:

- fix the textdomain for groups.
- add a trailing slash to the member URL when required.

https://onthegosystems.myjetbrains.com/youtrack/issue/bpml-13

2021-11-17 17:58 UTC, dgwatkins commented
@OnTheGoSystems/compatibility Please review

2021-11-17 19:42 UTC, strategio requested changes

2021-11-17 19:42 UTC, strategio commented on includes/class.groups.php
> +	const TEXTDOMAIN = 'Buddypress Multilingual';
@dgwatkins, we never released a version with the previous `bpml` text domain, right?

2021-11-17 19:42 UTC, strategio commented on includes/class.xprofile.php
> +    public function t_data( $data, $r ) {
Could you please add a PHPDoc?

And also, the method name `t_data` and the `$r` variable are not very meaningful, could we improve it? Or is there a naming pattern that I am not aware of, in this project?

2021-11-17 19:42 UTC, strategio commented on includes/class.xprofile.php
> +            $field_type = bp_xprofile_get_field_type( $field_id );
@dgwatkins, [bp_xprofile_get_field_type](https://wbremedy.com/reference/functions/bp_xprofile_get_field_type/) can return `null`. You should check the return value in the `if` condition.

2021-11-17 19:42 UTC, strategio commented on includes/class.xprofile.php
> +                    $this->_context,
If you decide to unify the text domain, then you should also "link" `WPML\BuddyPress\Groups::TEXTDOMAIN` and `$this->_context`.

Maybe:

```php
class BPML_XProfile implements \IWPML_Backend_Action, \IWPML_Frontend_Action {

    protected $_context = \WPML\BuddyPress\Groups::TEXTDOMAIN;

   //...

}
```

2021-11-18 09:48 UTC, dgwatkins commented on includes/class.groups.php
> +	const TEXTDOMAIN = 'Buddypress Multilingual';
Thats right

2021-11-18 11:23 UTC, dgwatkins commented on includes/class.xprofile.php
> +    public function t_data( $data, $r ) {
Added PHPDoc and renamed the `$r` argument too.

All the methods that translate in this class are named `t_xxxx`. I think its clear once you see the whole class.

2021-11-18 11:24 UTC, dgwatkins commented on includes/class.xprofile.php
> +            $field_type = bp_xprofile_get_field_type( $field_id );
Good catch, done

2021-11-18 11:27 UTC, dgwatkins commented on includes/class.xprofile.php
> +                    $this->_context,
Makes sense, linked.

2021-11-18 12:04 UTC, strategio approved these changes
+1 @dgwatkins

2021-11-19 02:55 UTC, kkarpieszuk approved these changes

2021-11-19 10:04 UTC, merged