Handle alternate_name:
OnTheGoSystems/buddypress-multilingual pull request #28
Opened 2021-11-18 17:02 UTC by dgwatkins

- Detect when it needs registering
- Bulk register it
- Register when adding/updating
- Unregister when deleting
- Translate it in the frontend

Please note this is a BuddyBoss only feature (not BuddyPress)

https://onthegosystems.myjetbrains.com/youtrack/issue/bpml-18

2021-11-18 17:03 UTC, dgwatkins commented
Can I have a review please @OnTheGoSystems/compatibility ?

2021-11-18 18:04 UTC, strategio requested changes

2021-11-18 18:04 UTC, strategio commented on includes/class.xprofile.php
> +        add_filter( 'bp_get_the_profile_field_name', array($this, 't_name'), 9 ); // Must run before name is replaced with alternate_name.
Maybe use a class constant instead of a comment @dgwatkins:

```php
const PRIORITY_BEFORE_NAME_REPLACE = 9;
```

2021-11-18 18:04 UTC, strategio commented on includes/class.xprofile.php
> +                        if ( ! empty( $meta ) ) {
```suggestion
                        if ( $meta ) {
```

2021-11-18 18:04 UTC, strategio commented on includes/class.xprofile.php
> +        if ( 'alternate_name' === $key && ! empty( $value ) ) {
```suggestion
        if ( 'alternate_name' === $key && $value ) {
```

2021-11-18 18:04 UTC, strategio commented on includes/class.xprofile.php
> +        return stripslashes( apply_filters( 'wpml_translate_single_string', $name, $this->_context, "{$this->_field_string_prefix}{$field->id} alternate name" ) );
@dgwatkins, this pattern `"{$this->_field_string_prefix}{$field->id} alternate name"` is repeated in many places (and even more things). I believe it's time to factorize a bit.

```php
private function translate( $value, $name_suffix ) {
    global $field;
    return stripslashes( apply_filters( 'wpml_translate_single_string', $value, $this->_context, "{$this->_field_string_prefix}{$field->id} $name_suffix" ) );
}

public function t_name( $value ) {
    return $this->translate( $value, 'name' );
}

public function t_alternate_name( $value ) {
    return $this->translate( $value, 'alternate name' );
}

//...
```

You should also try to do this for registering strings.

I see we also have a different pattern for options, not sure if we can easily/safely unify this, but it's probably the right time to try.

2021-11-18 18:04 UTC, strategio commented on includes/class.xprofile.php
> +                        if ( ! empty( $meta ) ) {
```suggestion
                        if ( $meta ) {
```

Sorry to be insistent, but it looks so much simpler to me :)

2021-11-18 18:07 UTC, dgwatkins commented on includes/class.xprofile.php
> +        add_filter( 'bp_get_the_profile_field_name', array($this, 't_name'), 9 ); // Must run before name is replaced with alternate_name.
done

2021-11-18 18:09 UTC, dgwatkins commented on includes/class.xprofile.php
> +                        if ( ! empty( $meta ) ) {
It's just habit ... and in this particular case, it was already all over the place.

I'll keep an eye on this in the future.

2021-11-18 18:10 UTC, dgwatkins commented on includes/class.xprofile.php
> +        return stripslashes( apply_filters( 'wpml_translate_single_string', $name, $this->_context, "{$this->_field_string_prefix}{$field->id} alternate name" ) );
I was reluctant to change existing code, so I followed the patterns I found.

But you are right, its the right time.

2021-11-18 18:38 UTC, dgwatkins commented on includes/class.xprofile.php
> +        return stripslashes( apply_filters( 'wpml_translate_single_string', $name, $this->_context, "{$this->_field_string_prefix}{$field->id} alternate name" ) );
Actually, I prefer merging bpml-13 before refactoring to avoid conflicts, I'll come back here later.

2021-11-19 11:32 UTC, dgwatkins commented on includes/class.xprofile.php
> +        return stripslashes( apply_filters( 'wpml_translate_single_string', $name, $this->_context, "{$this->_field_string_prefix}{$field->id} alternate name" ) );
@strategio I did some refactoring.

Can you take another look?

2021-11-22 11:23 UTC, strategio approved these changes
It looks good @dgwatkins, we're upgrading the code to something better.

Generally I try to avoid renaming the public methods unless it's really required. You changed the pattern from `t_name` to `translate_name`. It's way easier to read, but these little changes can always bring some issues... I'll leave the decision to you.

+1 from my part!

2021-11-22 11:32 UTC, dgwatkins commented
Thanks @strategio 

I will keep the changes this time and keep this in mind for next time.

2021-11-22 11:32 UTC, dgwatkins commented
Second review please @OnTheGoSystems/compatibility

2021-11-23 07:35 UTC, kkarpieszuk commented
+1

2021-11-23 10:08 UTC, merged